# Generated by Django 2.1.5 on 2020-08-26 14:50

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200826_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RuTag',
        ),
        migrations.DeleteModel(
            name='RuTaggedItem',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
