# Generated by Django 2.1.5 on 2020-09-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200826_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='TRELLO_ID',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
