# Generated by Django 2.1.5 on 2020-09-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_todoitem_trello_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='board_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
