# Generated by Django 2.1.5 on 2020-10-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_tagcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'Высокий приоритет'), (2, 'Средний приоритет'), (3, 'Низкий приоритет')], default=0, verbose_name='Приоритет')),
                ('priority_id', models.PositiveIntegerField(default=0)),
                ('priority_count', models.PositiveIntegerField(db_index=True, default=0)),
            ],
        ),
    ]
