# Generated by Django 2.1.5 on 2020-10-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_prioritycount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prioritycount',
            name='priority',
        ),
        migrations.AddField(
            model_name='prioritycount',
            name='priority_high',
            field=models.IntegerField(default=1, verbose_name='Высокий приоритет'),
        ),
        migrations.AddField(
            model_name='prioritycount',
            name='priority_low',
            field=models.IntegerField(default=3, verbose_name='Низкий приоритет'),
        ),
        migrations.AddField(
            model_name='prioritycount',
            name='priority_medium',
            field=models.IntegerField(default=2, verbose_name='Средний приоритет'),
        ),
    ]
